require 'stellar_sdk_payments_demo'

# Demo create account

SOURCE_SEED = "SBGWU2LWO3HHLALCREMUDNGYD2Q5R53K26ZBC4PTMGM5LF53MZRC6Q4Y"
DESTINATION = "GBU532MIR4NIUSOFHMX6QF36NI7V3WEEHDC3JFGY5RDPRCPYZAIUB76W"

StellarSdkPaymentsDemo::Client.create_account(SOURCE_SEED, DESTINATION)